server:
  port: 8001
  error:
    whitelabel:
      enabled: false

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
