//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.23 at 10:24:46 PM CEST 
//


package org.rub.nds.futuretrust.cvs.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authenticatedUserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authenticatedUserType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userAdditionalInformation" type="{http://www.api.sso.cvs.futuretrust.nds.rub.org}userAdditionalInformationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authenticatedUserType", propOrder = {
    "userID",
    "userAdditionalInformation"
})
public class AuthenticatedUserType {

    @XmlElement(required = true)
    protected String userID;
    protected UserAdditionalInformationType userAdditionalInformation;

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the userAdditionalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link UserAdditionalInformationType }
     *     
     */
    public UserAdditionalInformationType getUserAdditionalInformation() {
        return userAdditionalInformation;
    }

    /**
     * Sets the value of the userAdditionalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAdditionalInformationType }
     *     
     */
    public void setUserAdditionalInformation(UserAdditionalInformationType value) {
        this.userAdditionalInformation = value;
    }

}
