//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.23 at 10:24:46 PM CEST 
//


package org.rub.nds.futuretrust.cvs.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oidcType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oidcType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oidcResponse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="oidcVerificationProfile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="oidcVerificationParameters" type="{http://www.api.sso.cvs.futuretrust.nds.rub.org}oidcVerificationParametersType" minOccurs="0"/>
 *         &lt;element name="oidcVerificiationChecks" type="{http://www.api.sso.cvs.futuretrust.nds.rub.org}oidcVerificationChecksType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oidcType", propOrder = {
    "oidcResponse",
    "oidcVerificationProfile",
    "oidcVerificationParameters",
    "oidcVerificiationChecks"
})
public class OidcType {

    protected String oidcResponse;
    protected String oidcVerificationProfile;
    protected OidcVerificationParametersType oidcVerificationParameters;
    @XmlElement(required = true)
    protected OidcVerificationChecksType oidcVerificiationChecks;

    /**
     * Gets the value of the oidcResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOidcResponse() {
        return oidcResponse;
    }

    /**
     * Sets the value of the oidcResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOidcResponse(String value) {
        this.oidcResponse = value;
    }

    /**
     * Gets the value of the oidcVerificationProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOidcVerificationProfile() {
        return oidcVerificationProfile;
    }

    /**
     * Sets the value of the oidcVerificationProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOidcVerificationProfile(String value) {
        this.oidcVerificationProfile = value;
    }

    /**
     * Gets the value of the oidcVerificationParameters property.
     * 
     * @return
     *     possible object is
     *     {@link OidcVerificationParametersType }
     *     
     */
    public OidcVerificationParametersType getOidcVerificationParameters() {
        return oidcVerificationParameters;
    }

    /**
     * Sets the value of the oidcVerificationParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link OidcVerificationParametersType }
     *     
     */
    public void setOidcVerificationParameters(OidcVerificationParametersType value) {
        this.oidcVerificationParameters = value;
    }

    /**
     * Gets the value of the oidcVerificiationChecks property.
     * 
     * @return
     *     possible object is
     *     {@link OidcVerificationChecksType }
     *     
     */
    public OidcVerificationChecksType getOidcVerificiationChecks() {
        return oidcVerificiationChecks;
    }

    /**
     * Sets the value of the oidcVerificiationChecks property.
     * 
     * @param value
     *     allowed object is
     *     {@link OidcVerificationChecksType }
     *     
     */
    public void setOidcVerificiationChecks(OidcVerificationChecksType value) {
        this.oidcVerificiationChecks = value;
    }

}
