//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.23 at 10:24:46 PM CEST 
//


package org.rub.nds.futuretrust.cvs.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oidcVerificationChecksType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oidcVerificationChecksType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="verifyIssuer" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="verifyAudience" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="verifiyNonce" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="verifyIssuedAt" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="verifyExpired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="vierfyNotBefore" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="verifySubClaims" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oidcVerificationChecksType", propOrder = {
    "verifyIssuer",
    "verifyAudience",
    "verifiyNonce",
    "verifyIssuedAt",
    "verifyExpired",
    "vierfyNotBefore",
    "verifySubClaims"
})
public class OidcVerificationChecksType {

    protected boolean verifyIssuer;
    protected boolean verifyAudience;
    protected boolean verifiyNonce;
    protected boolean verifyIssuedAt;
    protected boolean verifyExpired;
    protected boolean vierfyNotBefore;
    protected boolean verifySubClaims;

    /**
     * Gets the value of the verifyIssuer property.
     * 
     */
    public boolean isVerifyIssuer() {
        return verifyIssuer;
    }

    /**
     * Sets the value of the verifyIssuer property.
     * 
     */
    public void setVerifyIssuer(boolean value) {
        this.verifyIssuer = value;
    }

    /**
     * Gets the value of the verifyAudience property.
     * 
     */
    public boolean isVerifyAudience() {
        return verifyAudience;
    }

    /**
     * Sets the value of the verifyAudience property.
     * 
     */
    public void setVerifyAudience(boolean value) {
        this.verifyAudience = value;
    }

    /**
     * Gets the value of the verifiyNonce property.
     * 
     */
    public boolean isVerifiyNonce() {
        return verifiyNonce;
    }

    /**
     * Sets the value of the verifiyNonce property.
     * 
     */
    public void setVerifiyNonce(boolean value) {
        this.verifiyNonce = value;
    }

    /**
     * Gets the value of the verifyIssuedAt property.
     * 
     */
    public boolean isVerifyIssuedAt() {
        return verifyIssuedAt;
    }

    /**
     * Sets the value of the verifyIssuedAt property.
     * 
     */
    public void setVerifyIssuedAt(boolean value) {
        this.verifyIssuedAt = value;
    }

    /**
     * Gets the value of the verifyExpired property.
     * 
     */
    public boolean isVerifyExpired() {
        return verifyExpired;
    }

    /**
     * Sets the value of the verifyExpired property.
     * 
     */
    public void setVerifyExpired(boolean value) {
        this.verifyExpired = value;
    }

    /**
     * Gets the value of the vierfyNotBefore property.
     * 
     */
    public boolean isVierfyNotBefore() {
        return vierfyNotBefore;
    }

    /**
     * Sets the value of the vierfyNotBefore property.
     * 
     */
    public void setVierfyNotBefore(boolean value) {
        this.vierfyNotBefore = value;
    }

    /**
     * Gets the value of the verifySubClaims property.
     * 
     */
    public boolean isVerifySubClaims() {
        return verifySubClaims;
    }

    /**
     * Sets the value of the verifySubClaims property.
     * 
     */
    public void setVerifySubClaims(boolean value) {
        this.verifySubClaims = value;
    }

}
