//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.23 at 10:24:46 PM CEST 
//


package org.rub.nds.futuretrust.cvs.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for proofOfPossessionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="proofOfPossessionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jwk" type="{http://www.api.sso.cvs.futuretrust.nds.rub.org}jwkType" minOccurs="0"/>
 *         &lt;element name="jwe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jku" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "proofOfPossessionType", propOrder = {
    "kid",
    "jwk",
    "jwe",
    "jku"
})
public class ProofOfPossessionType {

    protected String kid;
    protected JwkType jwk;
    protected String jwe;
    protected String jku;

    /**
     * Gets the value of the kid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKid() {
        return kid;
    }

    /**
     * Sets the value of the kid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKid(String value) {
        this.kid = value;
    }

    /**
     * Gets the value of the jwk property.
     * 
     * @return
     *     possible object is
     *     {@link JwkType }
     *     
     */
    public JwkType getJwk() {
        return jwk;
    }

    /**
     * Sets the value of the jwk property.
     * 
     * @param value
     *     allowed object is
     *     {@link JwkType }
     *     
     */
    public void setJwk(JwkType value) {
        this.jwk = value;
    }

    /**
     * Gets the value of the jwe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJwe() {
        return jwe;
    }

    /**
     * Sets the value of the jwe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJwe(String value) {
        this.jwe = value;
    }

    /**
     * Gets the value of the jku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJku() {
        return jku;
    }

    /**
     * Sets the value of the jku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJku(String value) {
        this.jku = value;
    }

}
