//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.23 at 10:24:46 PM CEST 
//


package org.rub.nds.futuretrust.cvs.sso.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for samlVerificationParametersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="samlVerificationParametersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="x509certificate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="samlSchema" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="samlSchema_url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="audience" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="time_limitation" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="hok_x509certificate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="saml_metadata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="saml_metadata_url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samlVerificationParametersType", propOrder = {
    "x509Certificate",
    "samlSchema",
    "samlSchemaUrl",
    "audience",
    "destination",
    "timeLimitation",
    "hokX509Certificate",
    "samlMetadata",
    "samlMetadataUrl"
})
public class SamlVerificationParametersType {

    @XmlElement(name = "x509certificate", required = true)
    protected String x509Certificate;
    protected List<String> samlSchema;
    @XmlElement(name = "samlSchema_url")
    protected String samlSchemaUrl;
    protected List<String> audience;
    protected String destination;
    @XmlElement(name = "time_limitation")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar timeLimitation;
    @XmlElement(name = "hok_x509certificate")
    protected String hokX509Certificate;
    @XmlElement(name = "saml_metadata")
    protected String samlMetadata;
    @XmlElement(name = "saml_metadata_url")
    protected String samlMetadataUrl;

    /**
     * Gets the value of the x509Certificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX509Certificate() {
        return x509Certificate;
    }

    /**
     * Sets the value of the x509Certificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX509Certificate(String value) {
        this.x509Certificate = value;
    }

    /**
     * Gets the value of the samlSchema property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the samlSchema property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSamlSchema().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSamlSchema() {
        if (samlSchema == null) {
            samlSchema = new ArrayList<String>();
        }
        return this.samlSchema;
    }

    /**
     * Gets the value of the samlSchemaUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamlSchemaUrl() {
        return samlSchemaUrl;
    }

    /**
     * Sets the value of the samlSchemaUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamlSchemaUrl(String value) {
        this.samlSchemaUrl = value;
    }

    /**
     * Gets the value of the audience property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audience property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudience().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAudience() {
        if (audience == null) {
            audience = new ArrayList<String>();
        }
        return this.audience;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the timeLimitation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeLimitation() {
        return timeLimitation;
    }

    /**
     * Sets the value of the timeLimitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeLimitation(XMLGregorianCalendar value) {
        this.timeLimitation = value;
    }

    /**
     * Gets the value of the hokX509Certificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHokX509Certificate() {
        return hokX509Certificate;
    }

    /**
     * Sets the value of the hokX509Certificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHokX509Certificate(String value) {
        this.hokX509Certificate = value;
    }

    /**
     * Gets the value of the samlMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamlMetadata() {
        return samlMetadata;
    }

    /**
     * Sets the value of the samlMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamlMetadata(String value) {
        this.samlMetadata = value;
    }

    /**
     * Gets the value of the samlMetadataUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamlMetadataUrl() {
        return samlMetadataUrl;
    }

    /**
     * Sets the value of the samlMetadataUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamlMetadataUrl(String value) {
        this.samlMetadataUrl = value;
    }

}
