//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.23 at 10:24:46 PM CEST 
//


package org.rub.nds.futuretrust.cvs.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for samlAuthnRequestVerificationChecksType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="samlAuthnRequestVerificationChecksType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="verifySchema" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifyXSW" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifyAuthnReqSignatureTrusted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifyAuthnReqSignature" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifyAuthnReqIssueInstant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="verifyAuthnReqID" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "samlAuthnRequestVerificationChecksType", propOrder = {
    "verifySchema",
    "verifyXSW",
    "verifyAuthnReqSignatureTrusted",
    "verifyAuthnReqSignature",
    "verifyAuthnReqIssueInstant",
    "verifyAuthnReqID"
})
public class SamlAuthnRequestVerificationChecksType {

    protected Boolean verifySchema;
    protected Boolean verifyXSW;
    protected Boolean verifyAuthnReqSignatureTrusted;
    protected Boolean verifyAuthnReqSignature;
    protected Boolean verifyAuthnReqIssueInstant;
    protected Boolean verifyAuthnReqID;

    /**
     * Gets the value of the verifySchema property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerifySchema() {
        return verifySchema;
    }

    /**
     * Sets the value of the verifySchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerifySchema(Boolean value) {
        this.verifySchema = value;
    }

    /**
     * Gets the value of the verifyXSW property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerifyXSW() {
        return verifyXSW;
    }

    /**
     * Sets the value of the verifyXSW property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerifyXSW(Boolean value) {
        this.verifyXSW = value;
    }

    /**
     * Gets the value of the verifyAuthnReqSignatureTrusted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerifyAuthnReqSignatureTrusted() {
        return verifyAuthnReqSignatureTrusted;
    }

    /**
     * Sets the value of the verifyAuthnReqSignatureTrusted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerifyAuthnReqSignatureTrusted(Boolean value) {
        this.verifyAuthnReqSignatureTrusted = value;
    }

    /**
     * Gets the value of the verifyAuthnReqSignature property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerifyAuthnReqSignature() {
        return verifyAuthnReqSignature;
    }

    /**
     * Sets the value of the verifyAuthnReqSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerifyAuthnReqSignature(Boolean value) {
        this.verifyAuthnReqSignature = value;
    }

    /**
     * Gets the value of the verifyAuthnReqIssueInstant property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerifyAuthnReqIssueInstant() {
        return verifyAuthnReqIssueInstant;
    }

    /**
     * Sets the value of the verifyAuthnReqIssueInstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerifyAuthnReqIssueInstant(Boolean value) {
        this.verifyAuthnReqIssueInstant = value;
    }

    /**
     * Gets the value of the verifyAuthnReqID property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerifyAuthnReqID() {
        return verifyAuthnReqID;
    }

    /**
     * Sets the value of the verifyAuthnReqID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerifyAuthnReqID(Boolean value) {
        this.verifyAuthnReqID = value;
    }

}
