//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.23 at 10:24:46 PM CEST 
//


package org.rub.nds.futuretrust.cvs.sso.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ssoProtocol_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ssoProtocol_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="saml"/>
 *     &lt;enumeration value="oidc"/>
 *     &lt;enumeration value="oauth"/>
 *     &lt;enumeration value="x509"/>
 *     &lt;enumeration value="config"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ssoProtocol_Type")
@XmlEnum
public enum SsoProtocolType {

    @XmlEnumValue("saml")
    SAML("saml"),
    @XmlEnumValue("oidc")
    OIDC("oidc"),
    @XmlEnumValue("oauth")
    OAUTH("oauth"),
    @XmlEnumValue("x509")
    X_509("x509"),
    @XmlEnumValue("config")
    CONFIG("config");
    private final String value;

    SsoProtocolType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SsoProtocolType fromValue(String v) {
        for (SsoProtocolType c: SsoProtocolType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
