//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.23 at 10:24:46 PM CEST 
//


package org.rub.nds.futuretrust.cvs.sso.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for verificationResponse_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="verificationResponse_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authenticatedUser" type="{http://www.api.sso.cvs.futuretrust.nds.rub.org}authenticatedUserType"/>
 *         &lt;choice>
 *           &lt;element name="samlAuthnRequestVerifiedChecks" type="{http://www.api.sso.cvs.futuretrust.nds.rub.org}samlAuthnRequestVerificationChecksType" minOccurs="0"/>
 *           &lt;element name="samlTokenVerifiedChecks" type="{http://www.api.sso.cvs.futuretrust.nds.rub.org}samlTokenVerificationChecksType" minOccurs="0"/>
 *           &lt;element name="oidcVerifiedChecks" type="{http://www.api.sso.cvs.futuretrust.nds.rub.org}oidcVerificationChecksType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="verificationLog" type="{http://www.api.sso.cvs.futuretrust.nds.rub.org}verificationLogType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "verificationResponse_Type", propOrder = {
    "authenticatedUser",
    "samlAuthnRequestVerifiedChecks",
    "samlTokenVerifiedChecks",
    "oidcVerifiedChecks",
    "verificationLog"
})
public class VerificationResponseType {

    @XmlElement(required = true)
    protected AuthenticatedUserType authenticatedUser;
    protected SamlAuthnRequestVerificationChecksType samlAuthnRequestVerifiedChecks;
    protected SamlTokenVerificationChecksType samlTokenVerifiedChecks;
    protected OidcVerificationChecksType oidcVerifiedChecks;
    @XmlElement(required = true)
    protected VerificationLogType verificationLog;

    /**
     * Gets the value of the authenticatedUser property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticatedUserType }
     *     
     */
    public AuthenticatedUserType getAuthenticatedUser() {
        return authenticatedUser;
    }

    /**
     * Sets the value of the authenticatedUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticatedUserType }
     *     
     */
    public void setAuthenticatedUser(AuthenticatedUserType value) {
        this.authenticatedUser = value;
    }

    /**
     * Gets the value of the samlAuthnRequestVerifiedChecks property.
     * 
     * @return
     *     possible object is
     *     {@link SamlAuthnRequestVerificationChecksType }
     *     
     */
    public SamlAuthnRequestVerificationChecksType getSamlAuthnRequestVerifiedChecks() {
        return samlAuthnRequestVerifiedChecks;
    }

    /**
     * Sets the value of the samlAuthnRequestVerifiedChecks property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamlAuthnRequestVerificationChecksType }
     *     
     */
    public void setSamlAuthnRequestVerifiedChecks(SamlAuthnRequestVerificationChecksType value) {
        this.samlAuthnRequestVerifiedChecks = value;
    }

    /**
     * Gets the value of the samlTokenVerifiedChecks property.
     * 
     * @return
     *     possible object is
     *     {@link SamlTokenVerificationChecksType }
     *     
     */
    public SamlTokenVerificationChecksType getSamlTokenVerifiedChecks() {
        return samlTokenVerifiedChecks;
    }

    /**
     * Sets the value of the samlTokenVerifiedChecks property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamlTokenVerificationChecksType }
     *     
     */
    public void setSamlTokenVerifiedChecks(SamlTokenVerificationChecksType value) {
        this.samlTokenVerifiedChecks = value;
    }

    /**
     * Gets the value of the oidcVerifiedChecks property.
     * 
     * @return
     *     possible object is
     *     {@link OidcVerificationChecksType }
     *     
     */
    public OidcVerificationChecksType getOidcVerifiedChecks() {
        return oidcVerifiedChecks;
    }

    /**
     * Sets the value of the oidcVerifiedChecks property.
     * 
     * @param value
     *     allowed object is
     *     {@link OidcVerificationChecksType }
     *     
     */
    public void setOidcVerifiedChecks(OidcVerificationChecksType value) {
        this.oidcVerifiedChecks = value;
    }

    /**
     * Gets the value of the verificationLog property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationLogType }
     *     
     */
    public VerificationLogType getVerificationLog() {
        return verificationLog;
    }

    /**
     * Sets the value of the verificationLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationLogType }
     *     
     */
    public void setVerificationLog(VerificationLogType value) {
        this.verificationLog = value;
    }

}
